create table if not exists public.urls (
    id bigint generated by default as identity primary key,
    url text not null,
    domain text not null,
    created_at timestamptz not null default now()
);

-- Daha önce yalnızca id/url/created_at ile oluşturulmuş MVP tablosunu yükseltir.
alter table public.urls add column if not exists domain text;
update public.urls
set domain = lower(
    regexp_replace(
        split_part(regexp_replace(url, '^https?://', '', 'i'), '/', 1),
        ':\d+$',
        ''
    )
)
where domain is null;
alter table public.urls alter column domain set not null;

create index if not exists urls_domain_idx on public.urls (domain);

create table if not exists public.analyses (
    id bigint generated by default as identity primary key,
    url_id bigint not null references public.urls(id) on delete cascade,
    domain_age_days integer,
    ssl_valid boolean,
    dns_data jsonb not null default '{}'::jsonb,
    whois_data jsonb not null default '{}'::jsonb,
    virustotal_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists analyses_url_id_idx on public.analyses (url_id);
create index if not exists analyses_created_at_idx on public.analyses (created_at desc);

create table if not exists public.risk_scores (
    id bigint generated by default as identity primary key,
    analysis_id bigint not null unique references public.analyses(id) on delete cascade,
    score smallint not null check (score between 0 and 100),
    status text not null check (status in ('safe', 'suspicious', 'dangerous')),
    reasons jsonb not null default '[]'::jsonb,
    ai_explanation text,
    created_at timestamptz not null default now()
);

create index if not exists risk_scores_created_at_idx on public.risk_scores (created_at desc);

alter table public.urls enable row level security;
alter table public.analyses enable row level security;
alter table public.risk_scores enable row level security;

-- Bu MVP'de tablolara yalnızca FastAPI içindeki service-role istemcisi erişir.
-- Tarayıcıdan doğrudan Supabase erişimi açılmadığı için public RLS policy oluşturulmaz.
